/**
 * Single source of truth for all site copy (EN / AR).
 *
 * Content rule: every fact here comes from the CV
 * (Brand_Identity_and_CV/Anas_Al_Tarayrah_CV.html), the brand guide, or this
 * repository. Do not add metrics, clients, hobbies or projects that cannot be verified.
 */

export const links = {
  email: 'anastarayra12@gmail.com',
  phoneDisplay: '+962 79 685 1497',
  whatsapp: 'https://wa.me/962796851497',
  linkedin: 'https://www.linkedin.com/in/anastarayra12',
  github: 'https://github.com/anastarayra12-ctrl',
  site: 'https://anas-portfolio-rose-nine.vercel.app/',
  cvPdf: '/Anas_AL-Tarayra-CV.pdf',
  cvFileName: 'Anas_Tarayra_CV.pdf',
  cvWeb: '/Anas_Al_Tarayrah_CV.html',
};

/** Page order = dock order. */
export const sectionIds = ['about', 'stack', 'work', 'journey', 'contact'];

/** Process nodes of the brand mark (logo geometry → meaning). */
export const processIds = ['idea', 'design', 'build', 'product'];

const en = {
  meta: {
    title: 'Anas Tarayra — Full-Stack Developer & UI/UX Designer',
    description:
      'Software Engineering student, full-stack developer and UI/UX designer in Amman, Jordan — turning ideas into designs and designs into digital products.',
  },
  a11y: {
    skip: 'Skip to content',
    themeToLight: 'Switch to light theme',
    themeToDark: 'Switch to dark theme',
    language: 'Language',
    darkMode: 'Dark mode',
    sections: 'Sections',
    backToTop: 'Back to top',
    newTab: '(opens in a new tab)',
    home: 'Anas Tarayra — back to top',
  },
  header: {
    name: 'Anas Tarayra',
    role: 'Full Stack Developer & UI/UX Designer',
    cv: 'CV',
    cvLong: 'Download CV',
    talk: "Let's Talk",
  },
  dock: {
    about: 'About Me',
    stack: 'Stack',
    work: 'My Work',
    journey: 'Journey',
    contact: 'Contact',
  },
  hero: {
    status: 'Available for work & collaborations',
    name: 'Anas Tarayra',
    roles: ['Software Engineering Student', 'Full Stack Developer', 'UI/UX Designer'],
    // The statement is split so its key words can light up their node in the mark.
    statement: [
      { t: 'Turning ' },
      { t: 'ideas', node: 'idea' },
      { t: ' into ' },
      { t: 'designs', node: 'design' },
      { t: ' and designs into ' },
      { t: 'digital products', node: 'product' },
      { t: '.' },
    ],
    primary: 'View My Work',
    secondary: 'Download CV',
    info: {
      location: 'Jordan, Amman',
      phoneLabel: 'Call or WhatsApp',
      languagesLabel: 'Languages',
      languages: [
        { name: 'Arabic', level: 'Native' },
        { name: 'English', level: 'Professional Working Proficiency' },
      ],
    },
    system: {
      label: 'Interactive brand mark: how an idea becomes a product',
      hint: 'Explore the process',
      steps: {
        idea: {
          n: '01',
          t: 'Idea',
          short: 'The spark',
          d: 'Every product starts as a thought. I turn it into a clear direction — the problem, the structure, the flow.',
        },
        design: {
          n: '02',
          t: 'Design',
          short: 'The experience',
          d: 'Where the idea becomes an experience. I shape how it looks, feels and works — in Figma, before a line of code.',
        },
        build: {
          n: '03',
          t: 'Build',
          short: 'The system',
          d: 'Where the experience becomes real. I engineer it with .NET and Angular — keeping the design intact.',
        },
        product: {
          n: '◆',
          t: 'Product',
          short: 'Where they meet',
          d: 'Design and build are two lines of the same “A”. They meet at the diamond — the digital product.',
        },
      },
    },
  },
  about: {
    index: '01',
    kicker: 'About Me',
    title: 'The Mind',
    intro: {
      title: 'About Anas',
      text: "I'm Anas, a third-year Software Engineering student at Al-Zaytoonah University of Jordan. I enjoy turning ideas into digital experiences and constantly exploring new ways to create, learn, and build.",
    },
    sides: [
      {
        key: 'dev',
        title: 'Anas as a Developer',
        text: "I'm a Full-Stack Developer working with .NET and Angular, and a Vibe Coder who uses AI-powered tools to explore ideas, build faster, and turn concepts into real digital products. I focus on creating practical, scalable, and well-structured solutions.",
        tags: ['.NET', 'Angular', 'AI-assisted'],
      },
      {
        key: 'design',
        title: 'Anas as a Designer',
        text: "I'm passionate about UI/UX and graphic design, with a focus on creating interfaces and visual identities that are simple, clear, and purposeful. For me, design is not just about how a product looks, but how it communicates and feels.",
        tags: ['UI/UX', 'Figma', 'Visual identity'],
      },
    ],
    quote: 'I want to be recognised for the quality of my work before any job title.',
    split: {
      label: 'Same card, two views — drag to compare code and design',
      code: 'Developer view',
      design: 'Designer view',
      hint: 'Drag',
      role: 'Full Stack Developer & UI/UX Designer',
      status: 'Available',
      cta: "Let's build",
    },
  },
  stack: {
    index: '02',
    kicker: 'Stack',
    title: 'What I Use',
    intro:
      'Tools I work with, and where I learned to use them. Each discipline highlights the tools I use and the courses that shaped my skills.',
    using: 'Using',
    learning: 'Learning',
    toolsLabel: 'Tools',
    learnedLabel: 'Learned through',
    reviewed: 'Reviewed by',
    inProgress: 'In progress',
    countTools: 'tools',
    countCourses: 'courses',
    choose: 'Choose a discipline',
    disciplines: [
      {
        key: 'design',
        name: 'Design',
        purpose: 'How it looks & feels',
        tools: [
          { t: 'Figma', note: 'Wireframing & prototyping' },
          { t: 'Adobe Photoshop' },
          { t: 'Design systems' },
          { t: 'Brand identity' },
        ],
        certs: [
          { title: 'UI/UX Design Masterclass', org: 'Udemy', by: 'Eng. Eslam Ameer', date: '2026' },
          { title: 'UI/UX Design Workshop', org: 'Zain Innovation Campus (ZINC)', by: 'Mr. Alaa Ali', date: '2026' },
          { title: 'Adobe Photoshop Course', org: 'YouTube', date: '2025' },
        ],
      },
      {
        key: 'engineering',
        name: 'Engineering',
        purpose: 'How it works',
        tools: [
          { t: 'ASP.NET', learning: true },
          { t: 'C#', learning: true },
          { t: 'Angular', learning: true },
          { t: 'TypeScript', learning: true },
          { t: 'REST APIs', learning: true },
          { t: 'React', note: 'This site' },
          { t: 'HTML5 & CSS' },
          { t: 'C++' },
        ],
        certs: [
          {
            title: 'Full Stack Developer (.NET & Angular)',
            org: 'Step by Step Company',
            by: 'Eng. Mohammad Al-Momani',
            date: 'In progress',
            live: true,
          },
        ],
      },
      {
        key: 'workflow',
        name: 'Workflow & AI',
        purpose: 'How it gets built faster',
        tools: [{ t: 'Git & GitHub' }, { t: 'Claude Code' }, { t: 'Prompt engineering' }, { t: 'Vibe coding' }],
        certs: [
          { title: 'Claude AI Mastery Course', org: 'Anthropic', date: '2026' },
          { title: 'Claude AI Prompt Engineering', org: 'YouTube', date: '2026' },
          { title: 'Vibe Coding Course', org: 'YouTube', date: '2026' },
        ],
      },
    ],
  },
  work: {
    index: '03',
    kicker: 'My Work',
    title: "What I've Built",
    intro: 'Real projects, documented honestly. Open a card to see the problem, what I did on each side, and how it was built.',
    labels: {
      open: 'View project',
      close: 'Close',
      problem: 'The problem',
      role: 'Role',
      year: 'Year',
      type: 'Type',
      status: 'Status',
      highlights: 'Highlights',
      design: 'Design',
      dev: 'Development',
      engineering: 'Under the hood',
      stack: 'Built with',
      outcome: 'Outcome',
      live: 'Visit live site',
      repo: 'Source on GitHub',
    },
    projects: [
      {
        id: 'portfolio',
        kind: 'Design + Engineering',
        year: '2026',
        status: 'Live',
        title: 'Personal portfolio',
        summary:
          'This site — designed from my own brand guide and engineered as a fast, bilingual, accessible single-page app.',
        problem:
          'A portfolio for someone who both designs and develops has to prove both at once. A template would show neither — the site itself had to be the evidence.',
        role: 'Designer & developer — end to end',
        highlights: [
          { t: 'Handwritten “hello” splash', d: 'One continuous SVG stroke drawn like the iPhone greeting, ending with the brand diamond. Skippable, and shown still for reduced-motion users.' },
          { t: 'The logo as a process', d: 'The brand mark explains how I work — Idea → Design → Build → Product — with layered 3D depth, a signal that travels the strokes, and cards attached to each node.' },
          { t: 'Code ⇄ Design comparison', d: 'The same profile card shown as JSX/CSS and as a designed frame, with a draggable divider that the About cards steer.' },
          { t: 'Transitions tied to my two sides', d: 'Switching theme grows a Figma-style selection frame; switching language sweeps an editor pane while an <html lang dir> diff is typed.' },
          { t: 'Two navigation layers', d: 'An identity header with language and theme switches, plus a floating section dock that tracks where you are.' },
          { t: 'Blueprint backdrop', d: 'A page-wide grid with a cursor spotlight that reveals glowing intersections — one background system instead of per-section decoration.' },
        ],
        design: [
          'Design system derived from the brand guide: palette, type scale, spacing, radius and motion tokens',
          'Brand fonts for both scripts: Space Grotesk, Lalezar and Changa',
          'Light and dark themes designed separately, not inverted',
          'Layouts designed per breakpoint, from 320px phones to wide screens',
        ],
        dev: [
          'React 19 + Vite, one component per section and a single bilingual content source',
          'English / Arabic with genuine right-to-left layout',
          'Scroll-aware navigation, focus management and keyboard control for every interactive piece',
          'A contact form that never fakes success: Web3Forms when configured, the visitor’s email app otherwise',
        ],
        engineering: [
          { k: 'Performance', v: 'Animation features load asynchronously; Three.js is split out and only loads for the maintenance screen; WOFF2 fonts with preloading.' },
          { k: 'Accessibility', v: 'Semantic structure, visible focus states, ARIA where it helps, and a reduced-motion version of every effect.' },
          { k: 'SEO', v: 'Meta and Open Graph tags, a custom share image, JSON-LD, sitemap and robots.txt.' },
          { k: 'Quality', v: 'Checked at 14 viewport widths in both languages and themes for overflow and console errors.' },
        ],
        stack: ['React 19', 'Vite', 'Framer Motion', 'CSS custom properties', 'SVG', 'Web3Forms', 'Vercel'],
        outcome: 'One consistent product that presents my work — and is part of it.',
        link: { href: 'https://anas-portfolio-rose-nine.vercel.app/' },
        repo: 'https://github.com/anastarayra12-ctrl/Anas-Portfolio-',
      },
      {
        id: 'brand',
        kind: 'Brand & Visual identity',
        year: '2026',
        status: 'Complete',
        title: 'Personal brand identity',
        summary:
          'A complete visual identity — logo, palette, bilingual typography and usage rules — documented in an 11-page guide.',
        problem:
          'I needed one identity that works across my portfolio, CV and LinkedIn — in Arabic and English, on screen and in print.',
        role: 'Brand designer',
        highlights: [
          { t: 'A logo with a meaning', d: 'An “A” of two lines meeting at a point, three connection nodes, and a diamond for where design meets technical execution.' },
          { t: 'A palette with rules', d: 'Colours extracted from the logo and used 60 / 30 / 10 — black, deep and accent blue, and sky as a light touch.' },
          { t: 'Two scripts, one voice', d: 'Space Grotesk for Latin text, Lalezar for Arabic headlines and Changa for Arabic body text.' },
        ],
        design: [
          'Palette extracted from the logo, with a 60 / 30 / 10 usage rule',
          'Three-typeface system: Space Grotesk, Lalezar and Changa',
          'Clear-space, minimum-size and do / don’t rules; LinkedIn cover and post templates',
        ],
        dev: [
          'Wrote the guide itself in HTML & CSS with embedded brand fonts',
          'Automated PDF and asset export with Node.js and Puppeteer scripts',
        ],
        engineering: [],
        stack: ['Visual identity', 'Typography', 'HTML & CSS', 'Node.js', 'Puppeteer'],
        outcome: 'One consistent identity, now used across this site, my CV and my LinkedIn presence.',
        link: null,
        repo: null,
      },
    ],
    empty: {
      title: 'Next up: full-stack projects',
      text: 'Work from my current .NET & Angular program will be documented here as it is completed.',
      cta: 'Follow on GitHub',
    },
  },
  journey: {
    index: '04',
    kicker: 'Journey',
    title: 'How I Got Here',
    intro: 'Not a list of dates — the steps where design and engineering started to become one practice.',
    here: 'You are here',
    chapters: [
      {
        key: 'foundation',
        mark: 'Start',
        tag: 'Foundation',
        title: 'Software Engineering at university',
        text: 'B.Sc. Software Engineering at Al-Zaytoonah University of Jordan — the engineering foundation everything else stands on. Now in my third year.',
      },
      {
        key: '2025',
        mark: '2025',
        tag: 'Design eye & leadership',
        title: 'Learning to see, learning to lead',
        text: 'Picked up Adobe Photoshop and graphic design, and became Academic & Technical Leader of a student team at my university.',
      },
      {
        key: '2026',
        mark: '2026',
        tag: 'Design meets code',
        title: 'The two sides connect',
        text: 'Studied UI/UX through a Udemy masterclass and a workshop at Zain Innovation Campus, brought AI into my workflow with Claude, and designed my brand identity and this portfolio end to end.',
      },
      {
        key: 'now',
        mark: 'Now',
        tag: 'Going full stack',
        title: 'Building the whole product',
        text: 'Deepening full-stack development with .NET and Angular in the Step by Step program — so I can build every layer of what I design.',
        current: true,
      },
      {
        key: '2028',
        mark: '2028',
        tag: 'Next',
        title: 'Graduation',
        text: 'Expected graduation — with a portfolio of products that are both designed and built.',
        future: true,
      },
    ],
  },
  contact: {
    index: '05',
    kicker: 'Contact',
    title: "Let's Build Something",
    intro: 'Have an idea, an internship, or a product to design and build? Tell me about it.',
    emailLabel: 'Write to me',
    copy: 'Copy email address',
    copied: 'Copied',
    elsewhere: 'Elsewhere',
    location: 'Amman, Jordan · UTC+3',
    cvWeb: 'CV — web version',
    form: {
      title: 'Or send a message here',
      name: 'Name',
      namePh: 'Your name',
      email: 'Email',
      emailPh: 'you@example.com',
      message: 'Message',
      messagePh: 'What are you working on?',
      send: 'Send message',
      sending: 'Sending…',
      errors: {
        name: 'Please enter your name.',
        email: 'Please enter a valid email address.',
        message: 'Please write a message of at least 10 characters.',
      },
      success: 'Thank you — your message was sent. I’ll get back to you soon.',
      mailtoOpened: 'Your email app should open with the message ready. If it didn’t, email me directly at',
      failure: 'The message couldn’t be sent. Please try again, or email me directly at',
      another: 'Send another message',
    },
  },
  footer: {
    signoff: 'Designed & developed by Anas Tarayra in Amman.',
    built: 'React · Vite · Space Grotesk',
    rights: 'All rights reserved.',
  },
};

const ar = {
  meta: {
    title: 'أنس الطرايرة — مطوّر Full-Stack ومصمّم UI/UX',
    description:
      'طالب هندسة برمجيات ومطوّر Full-Stack ومصمّم UI/UX في عمّان، الأردن — أحوّل الأفكار إلى تصاميم، والتصاميم إلى منتجات رقمية.',
  },
  a11y: {
    skip: 'تخطَّ إلى المحتوى',
    themeToLight: 'التبديل إلى المظهر الفاتح',
    themeToDark: 'التبديل إلى المظهر الداكن',
    language: 'اللغة',
    darkMode: 'الوضع الداكن',
    sections: 'الأقسام',
    backToTop: 'العودة للأعلى',
    newTab: '(يفتح في نافذة جديدة)',
    home: 'أنس الطرايرة — العودة للأعلى',
  },
  header: {
    name: 'أنس الطرايرة',
    role: 'مطوّر Full Stack ومصمّم UI/UX',
    cv: 'السيرة',
    cvLong: 'تحميل السيرة الذاتية',
    talk: 'لنتحدّث',
  },
  dock: {
    about: 'عنّي',
    stack: 'الأدوات',
    work: 'أعمالي',
    journey: 'المسيرة',
    contact: 'تواصل',
  },
  hero: {
    status: 'متاح للعمل والتعاون',
    name: 'أنس الطرايرة',
    roles: ['طالب هندسة برمجيات', 'مطوّر Full Stack', 'مصمّم UI/UX'],
    statement: [
      { t: 'أحوّل ' },
      { t: 'الأفكار', node: 'idea' },
      { t: ' إلى ' },
      { t: 'تصاميم', node: 'design' },
      { t: '، والتصاميم إلى ' },
      { t: 'منتجات رقمية', node: 'product' },
      { t: '.' },
    ],
    primary: 'استعرض أعمالي',
    secondary: 'تحميل السيرة الذاتية',
    info: {
      location: 'الأردن، عمّان',
      phoneLabel: 'اتصال أو واتساب',
      languagesLabel: 'اللغات',
      languages: [
        { name: 'العربية', level: 'اللغة الأم' },
        { name: 'الإنجليزية', level: 'كفاءة مهنية في العمل' },
      ],
    },
    system: {
      label: 'شعار تفاعلي: كيف تتحوّل الفكرة إلى منتج',
      hint: 'استكشف طريقة العمل',
      steps: {
        idea: {
          n: '01',
          t: 'الفكرة',
          short: 'الشرارة',
          d: 'كل منتج يبدأ بفكرة. أحوّلها إلى اتجاه واضح — المشكلة، والهيكل، ومسار الاستخدام.',
        },
        design: {
          n: '02',
          t: 'التصميم',
          short: 'التجربة',
          d: 'هنا تصبح الفكرة تجربة. أشكّل شكلها وإحساسها وطريقة عملها — في Figma، قبل أي سطر كود.',
        },
        build: {
          n: '03',
          t: 'البناء',
          short: 'النظام',
          d: 'هنا تصبح التجربة حقيقة. أبنيها بـ ⁦.NET⁩ وAngular — مع الحفاظ على التصميم كما هو.',
        },
        product: {
          n: '◆',
          t: 'المنتج',
          short: 'نقطة الالتقاء',
          d: 'التصميم والبناء خطّان من حرف «A» نفسه، يلتقيان عند المعيّن — المنتج الرقمي.',
        },
      },
    },
  },
  about: {
    index: '01',
    kicker: 'عنّي',
    title: 'طريقة التفكير',
    intro: {
      title: 'عن أنس',
      text: 'أنا أنس، طالب هندسة برمجيات في السنة الثالثة في جامعة الزيتونة الأردنية. أستمتع بتحويل الأفكار إلى تجارب رقمية، وأبحث باستمرار عن طرق جديدة للإبداع والتعلّم والبناء.',
    },
    sides: [
      {
        key: 'dev',
        title: 'أنس كمطوّر',
        text: 'أنا مطوّر Full-Stack أعمل بـ ⁦.NET⁩ وAngular، وVibe Coder أستخدم أدوات الذكاء الاصطناعي لاستكشاف الأفكار والبناء بشكل أسرع وتحويل المفاهيم إلى منتجات رقمية حقيقية. أركّز على بناء حلول عملية وقابلة للتوسّع ومنظّمة بشكل جيد.',
        tags: ['.NET', 'Angular', 'الذكاء الاصطناعي'],
      },
      {
        key: 'design',
        title: 'أنس كمصمّم',
        text: 'أنا شغوف بتصميم الواجهات وتجربة المستخدم والتصميم الجرافيكي، وأركّز على صنع واجهات وهويات بصرية بسيطة وواضحة وهادفة. التصميم بالنسبة لي ليس فقط شكل المنتج، بل كيف يتواصل وكيف يُشعِر.',
        tags: ['UI/UX', 'Figma', 'الهوية البصرية'],
      },
    ],
    quote: 'أريد أن أُعرف بجودة عملي قبل أي مسمّى وظيفي.',
    split: {
      label: 'البطاقة نفسها بعينين — اسحب للمقارنة بين الكود والتصميم',
      code: 'عين المطوّر',
      design: 'عين المصمّم',
      hint: 'اسحب',
      role: 'Full Stack Developer & UI/UX Designer',
      status: 'Available',
      cta: "Let's build",
    },
  },
  stack: {
    index: '02',
    kicker: 'الأدوات',
    title: 'ما أستخدمه',
    intro: 'الأدوات التي أعمل بها، وأين تعلّمت استخدامها. كل تخصّص يُبرز الأدوات التي أستخدمها والدورات التي صقلت مهاراتي.',
    using: 'أستخدمها',
    learning: 'قيد التعلّم',
    toolsLabel: 'الأدوات',
    learnedLabel: 'تعلّمتها عبر',
    reviewed: 'بمراجعة',
    inProgress: 'قيد الإنجاز',
    countTools: 'أدوات',
    countCourses: 'دورات',
    choose: 'اختر تخصّصًا',
    disciplines: [
      {
        key: 'design',
        name: 'التصميم',
        purpose: 'كيف يبدو ويُشعِر',
        tools: [
          { t: 'Figma', note: 'Wireframes ونماذج تفاعلية' },
          { t: 'Adobe Photoshop' },
          { t: 'أنظمة التصميم' },
          { t: 'الهوية البصرية' },
        ],
        certs: [
          { title: 'UI/UX Design Masterclass', org: 'Udemy', by: 'م. إسلام أمير', date: '2026' },
          { title: 'ورشة تصميم الواجهات وتجربة المستخدم', org: 'منصة زين للإبداع (ZINC)', by: 'أ. علاء علي', date: '2026' },
          { title: 'دورة Adobe Photoshop', org: 'YouTube', date: '2025' },
        ],
      },
      {
        key: 'engineering',
        name: 'الهندسة',
        purpose: 'كيف يعمل',
        tools: [
          { t: 'ASP.NET', learning: true },
          { t: 'C#', learning: true },
          { t: 'Angular', learning: true },
          { t: 'TypeScript', learning: true },
          { t: 'REST APIs', learning: true },
          { t: 'React', note: 'هذا الموقع' },
          { t: 'HTML5 & CSS' },
          { t: 'C++' },
        ],
        certs: [
          {
            title: 'مطوّر Full Stack ‏(.NET & Angular)',
            org: 'شركة Step by Step',
            by: 'م. محمد المومني',
            date: 'قيد الإنجاز',
            live: true,
          },
        ],
      },
      {
        key: 'workflow',
        name: 'سير العمل والذكاء الاصطناعي',
        purpose: 'كيف يُبنى أسرع',
        tools: [{ t: 'Git & GitHub' }, { t: 'Claude Code' }, { t: 'هندسة الأوامر' }, { t: 'Vibe Coding' }],
        certs: [
          { title: 'Claude AI Mastery Course', org: 'Anthropic', date: '2026' },
          { title: 'هندسة الأوامر لـ Claude', org: 'YouTube', date: '2026' },
          { title: 'دورة Vibe Coding', org: 'YouTube', date: '2026' },
        ],
      },
    ],
  },
  work: {
    index: '03',
    kicker: 'أعمالي',
    title: 'ما بنيته',
    intro: 'مشاريع حقيقية موثّقة بصدق. افتح أي بطاقة لترى المشكلة، وما قدّمته في كل جانب، وكيف بُنيت.',
    labels: {
      open: 'عرض المشروع',
      close: 'إغلاق',
      problem: 'المشكلة',
      role: 'الدور',
      year: 'السنة',
      type: 'النوع',
      status: 'الحالة',
      highlights: 'أبرز ما فيه',
      design: 'التصميم',
      dev: 'التطوير',
      engineering: 'تحت الغطاء',
      stack: 'التقنيات',
      outcome: 'النتيجة',
      live: 'زيارة الموقع',
      repo: 'الكود على GitHub',
    },
    projects: [
      {
        id: 'portfolio',
        kind: 'تصميم + هندسة',
        year: '2026',
        status: 'منشور',
        title: 'الموقع الشخصي',
        summary: 'هذا الموقع — مصمّم انطلاقًا من دليل هويتي البصرية، ومبني كتطبيق صفحة واحدة سريع وثنائي اللغة وسهل الوصول.',
        problem:
          'موقع لشخص يصمّم ويطوّر يجب أن يثبت الأمرين معًا. القالب الجاهز لا يثبت أيًّا منهما — كان على الموقع نفسه أن يكون الدليل.',
        role: 'مصمّم ومطوّر — من البداية للنهاية',
        highlights: [
          { t: 'شاشة ترحيب بخط اليد', d: 'كلمة hello تُكتب بخط واحد متصل مثل ترحيب iPhone، وتنتهي بمعيّن الهوية. يمكن تخطيها، وتظهر ثابتة لمن يفضّل تقليل الحركة.' },
          { t: 'الشعار كطريقة عمل', d: 'يشرح الشعار طريقة عملي — فكرة ← تصميم ← بناء ← منتج — بعمق ثلاثي الأبعاد، وإشارة تسري على الخطوط، وبطاقات ملتصقة بكل نقطة.' },
          { t: 'مقارنة الكود والتصميم', d: 'البطاقة التعريفية نفسها ككود JSX/CSS وكتصميم نهائي، بفاصل قابل للسحب تتحكّم به بطاقتا المطوّر والمصمّم.' },
          { t: 'تأثيرات مرتبطة بجانبيّ', d: 'تبديل المظهر يطلق إطار تحديد بأسلوب Figma، وتبديل اللغة يمسح الصفحة بمحرر كود بينما يُكتب تعديل ⁦<html lang dir>⁩.' },
          { t: 'طبقتا تنقّل', d: 'ترويسة للهوية فيها مفتاحا اللغة والمظهر، وشريط أقسام عائم يعرف أين أنت في الصفحة.' },
          { t: 'خلفية هندسية', d: 'شبكة تغطي الصفحة مع ضوء يتبع المؤشر ويكشف نقاط تقاطع مضيئة — نظام خلفية واحد بدل زخارف لكل قسم.' },
        ],
        design: [
          'نظام تصميم مشتق من دليل الهوية: الألوان، مقاييس الخطوط، المسافات، الزوايا والحركة',
          'خطوط الهوية للغتين: Space Grotesk وLalezar وChanga',
          'مظهر فاتح وداكن مصمّمان بشكل مستقل، لا مجرد عكس للألوان',
          'تخطيطات مصمّمة لكل مقاس، من هواتف 320px إلى الشاشات العريضة',
        ],
        dev: [
          'React 19 وVite، مكوّن لكل قسم ومصدر محتوى واحد باللغتين',
          'عربي / إنجليزي مع اتجاه حقيقي من اليمين لليسار',
          'تنقّل يتبع التمرير، وإدارة للتركيز، وتحكّم بلوحة المفاتيح في كل عنصر تفاعلي',
          'نموذج تواصل لا يدّعي النجاح كذبًا: Web3Forms عند ضبطه، وإلا تطبيق البريد لدى الزائر',
        ],
        engineering: [
          { k: 'الأداء', v: 'ميزات الحركة تُحمَّل لاحقًا؛ Three.js مفصولة ولا تُحمَّل إلا لشاشة الصيانة؛ خطوط WOFF2 مع تحميل مسبق.' },
          { k: 'سهولة الوصول', v: 'بنية دلالية، حالات تركيز واضحة، ARIA حيث يفيد، ونسخة بحركة مخفّفة من كل تأثير.' },
          { k: 'محركات البحث', v: 'وسوم Meta وOpen Graph، صورة مشاركة مخصّصة، JSON-LD، وملفّا sitemap وrobots.txt.' },
          { k: 'الجودة', v: 'فُحص على 14 مقاسًا باللغتين والمظهرين للتأكد من عدم وجود تمرير أفقي أو أخطاء.' },
        ],
        stack: ['React 19', 'Vite', 'Framer Motion', 'CSS custom properties', 'SVG', 'Web3Forms', 'Vercel'],
        outcome: 'منتج واحد متّسق يعرض أعمالي — وهو جزء منها.',
        link: { href: 'https://anas-portfolio-rose-nine.vercel.app/' },
        repo: 'https://github.com/anastarayra12-ctrl/Anas-Portfolio-',
      },
      {
        id: 'brand',
        kind: 'هوية بصرية',
        year: '2026',
        status: 'مكتمل',
        title: 'الهوية البصرية الشخصية',
        summary: 'هوية بصرية كاملة — شعار، ألوان، نظام خطوط ثنائي اللغة وقواعد استخدام — موثّقة في دليل من 11 صفحة.',
        problem:
          'احتجت هوية واحدة تعمل عبر موقعي وسيرتي الذاتية وLinkedIn — بالعربية والإنجليزية، على الشاشة وفي الطباعة.',
        role: 'مصمّم الهوية',
        highlights: [
          { t: 'شعار له معنى', d: 'حرف A من خطين يلتقيان بنقطة، وثلاث نقاط اتصال، ومعيّن يرمز لالتقاء التصميم بالتنفيذ التقني.' },
          { t: 'ألوان بقواعد', d: 'ألوان مستخرجة من الشعار بنسبة 60 / 30 / 10 — الأسود، والأزرق الغامق والمتوسط، والسماوي كلمسة خفيفة.' },
          { t: 'خطّان للغتين وصوت واحد', d: 'Space Grotesk للنص اللاتيني، وLalezar للعناوين العربية، وChanga للنصوص العربية.' },
        ],
        design: [
          'لوحة ألوان مستخرجة من الشعار مع قاعدة استخدام 60 / 30 / 10',
          'نظام من ثلاثة خطوط: Space Grotesk وLalezar وChanga',
          'قواعد مساحة الأمان والحد الأدنى للحجم والاستخدام الصحيح والخاطئ، وقوالب LinkedIn',
        ],
        dev: ['كتبت الدليل نفسه بـ HTML وCSS مع تضمين خطوط الهوية', 'أتمتة تصدير ملف PDF والأصول باستخدام Node.js وPuppeteer'],
        engineering: [],
        stack: ['هوية بصرية', 'الطباعة والخطوط', 'HTML & CSS', 'Node.js', 'Puppeteer'],
        outcome: 'هوية واحدة متّسقة، أستخدمها الآن في هذا الموقع وسيرتي الذاتية وحضوري على LinkedIn.',
        link: null,
        repo: null,
      },
    ],
    empty: {
      title: 'التالي: مشاريع Full-Stack',
      text: 'سأوثّق هنا أعمال برنامج ⁦.NET⁩ وAngular الحالي عند اكتمالها.',
      cta: 'تابعني على GitHub',
    },
  },
  journey: {
    index: '04',
    kicker: 'المسيرة',
    title: 'كيف وصلت إلى هنا',
    intro: 'ليست قائمة تواريخ — بل الخطوات التي بدأ فيها التصميم والهندسة يصبحان ممارسة واحدة.',
    here: 'أنت هنا',
    chapters: [
      {
        key: 'foundation',
        mark: 'البداية',
        tag: 'الأساس',
        title: 'هندسة البرمجيات في الجامعة',
        text: 'بكالوريوس هندسة البرمجيات في جامعة الزيتونة الأردنية — الأساس الهندسي الذي يقوم عليه كل شيء. أدرس حاليًا في السنة الثالثة.',
      },
      {
        key: '2025',
        mark: '2025',
        tag: 'عين المصمّم والقيادة',
        title: 'أتعلّم أن أرى، وأن أقود',
        text: 'تعلّمت Adobe Photoshop والتصميم الجرافيكي، وأصبحت قائدًا أكاديميًا وتقنيًا لفريق طلابي في جامعتي.',
      },
      {
        key: '2026',
        mark: '2026',
        tag: 'التصميم يلتقي بالكود',
        title: 'الجانبان يتّصلان',
        text: 'درست تصميم الواجهات وتجربة المستخدم عبر دورة على Udemy وورشة في منصة زين للإبداع، وأدخلت الذكاء الاصطناعي إلى سير عملي مع Claude، وصمّمت هويتي البصرية وهذا الموقع من البداية للنهاية.',
      },
      {
        key: 'now',
        mark: 'الآن',
        tag: 'نحو Full Stack',
        title: 'بناء المنتج كاملًا',
        text: 'أعمّق تطوير Full-Stack بـ ⁦.NET⁩ وAngular في برنامج Step by Step — لأبني كل طبقة مما أصمّمه.',
        current: true,
      },
      {
        key: '2028',
        mark: '2028',
        tag: 'التالي',
        title: 'التخرّج',
        text: 'التخرّج المتوقّع — مع مجموعة من المنتجات المصمّمة والمبنيّة معًا.',
        future: true,
      },
    ],
  },
  contact: {
    index: '05',
    kicker: 'تواصل',
    title: 'لنبنِ شيئًا معًا',
    intro: 'لديك فكرة، أو فرصة تدريب، أو منتج تريد تصميمه وبناءه؟ حدّثني عنه.',
    emailLabel: 'راسلني',
    copy: 'نسخ البريد الإلكتروني',
    copied: 'تم النسخ',
    elsewhere: 'في أماكن أخرى',
    location: 'عمّان، الأردن · UTC+3',
    cvWeb: 'السيرة الذاتية — نسخة الويب',
    form: {
      title: 'أو أرسل رسالة من هنا',
      name: 'الاسم',
      namePh: 'اسمك',
      email: 'البريد الإلكتروني',
      emailPh: 'you@example.com',
      message: 'الرسالة',
      messagePh: 'على ماذا تعمل؟',
      send: 'إرسال الرسالة',
      sending: 'جارٍ الإرسال…',
      errors: {
        name: 'يرجى إدخال اسمك.',
        email: 'يرجى إدخال بريد إلكتروني صحيح.',
        message: 'يرجى كتابة رسالة من 10 أحرف على الأقل.',
      },
      success: 'شكرًا لك — وصلت رسالتك، وسأردّ عليك قريبًا.',
      mailtoOpened: 'يُفترض أن يفتح تطبيق البريد والرسالة جاهزة. إن لم يحدث، راسلني مباشرة على',
      failure: 'تعذّر إرسال الرسالة. حاول مجددًا، أو راسلني مباشرة على',
      another: 'إرسال رسالة أخرى',
    },
  },
  footer: {
    signoff: 'صمّمه وطوّره أنس الطرايرة في عمّان.',
    built: 'React · Vite · Changa',
    rights: 'جميع الحقوق محفوظة.',
  },
};

export const content = { en, ar };
