/**
 * Single source of truth for all site copy (EN / AR).
 *
 * Content rule: every fact here comes from the CV
 * (Brand_Identity_and_CV/Anas_Al_Tarayrah_CV.html), the brand guide, or this
 * repository. Do not add metrics, clients, hobbies or projects that cannot be verified.
 */

export const links = {
  email: 'anastarayra12@gmail.com',
  phoneDisplay: '+962 79 685 1497',
  whatsapp: 'https://wa.me/962796851497',
  linkedin: 'https://www.linkedin.com/in/anastarayra12',
  github: 'https://github.com/anastarayra12',
  site: 'https://anas-portfolio-rose-nine.vercel.app/',
  cvPdf: '/Anas_AL-Tarayra-CV.pdf',
  cvFileName: 'Anas_Tarayra_CV.pdf',
  cvWeb: '/Anas_Al_Tarayrah_CV.html',
};

/** Page order = dock order. */
export const sectionIds = ['about', 'stack', 'work', 'journey', 'contact'];

/** Process nodes of the brand mark (logo geometry → meaning). */
export const processIds = ['idea', 'design', 'build', 'product'];

const en = {
  meta: {
    title: 'Anas Tarayra — Full-Stack Developer & UI/UX Designer',
    description:
      'Software Engineering student, full-stack developer and UI/UX designer in Amman, Jordan — turning ideas into designs and designs into digital products.',
  },
  a11y: {
    skip: 'Skip to content',
    themeToLight: 'Switch to light theme',
    themeToDark: 'Switch to dark theme',
    language: 'Language',
    darkMode: 'Dark mode',
    sections: 'Sections',
    backToTop: 'Back to top',
    newTab: '(opens in a new tab)',
    home: 'Anas Tarayra — back to top',
  },
  header: {
    name: 'Anas Tarayra',
    role: 'Full Stack Developer & UI/UX Designer',
    cv: 'CV',
    cvLong: 'Download CV',
    talk: "Let's Talk",
  },
  dock: {
    about: 'About Me',
    stack: 'Stack',
    work: 'My Work',
    journey: 'Journey',
    contact: 'Contact',
  },
  hero: {
    status: 'Available for work & collaborations',
    name: 'Anas Tarayra',
    roles: ['Software Engineering Student', 'Full Stack Developer', 'UI/UX Designer'],
    // The statement is split so its key words can light up their node in the mark.
    statement: [
      { t: 'Turning ' },
      { t: 'ideas', node: 'idea' },
      { t: ' into ' },
      { t: 'designs', node: 'design' },
      { t: ' and designs into ' },
      { t: 'digital products', node: 'product' },
      { t: '.' },
    ],
    primary: 'View My Work',
    secondary: 'Download CV',
    info: {
      location: 'Jordan, Amman',
      phoneLabel: 'Call or WhatsApp',
      languagesLabel: 'Languages',
      languages: [
        { name: 'Arabic', level: 'Native' },
        { name: 'English', level: 'Professional Working Proficiency' },
      ],
    },
    system: {
      label: 'Interactive brand mark: how an idea becomes a product',
      hint: 'Explore the process',
      steps: {
        idea: {
          n: '01',
          t: 'Idea',
          short: 'The spark',
          d: 'Every product starts as a thought. I turn it into a clear direction — the problem, the structure, the flow.',
        },
        design: {
          n: '02',
          t: 'Design',
          short: 'The experience',
          d: 'Where the idea becomes an experience. I shape how it looks, feels and works — in Figma, before a line of code.',
        },
        build: {
          n: '03',
          t: 'Build',
          short: 'The system',
          d: 'Where the experience becomes real. I engineer it with .NET and Angular — keeping the design intact.',
        },
        product: {
          n: '◆',
          t: 'Product',
          short: 'Where they meet',
          d: 'Design and build are two lines of the same “A”. They meet at the diamond — the digital product.',
        },
      },
    },
  },
  about: {
    index: '01',
    kicker: 'About Me',
    title: 'The Mind',
    lead: 'I think about a product from two directions at once — how it works, and how it feels.',
    body: [
      "I'm Anas, a third-year Software Engineering student at Al-Zaytoonah University of Jordan and a full-stack developer working with .NET and Angular — with a strong passion for UI/UX and graphic design.",
      'I believe the best digital products are created when design and development work together from the very beginning. So I build ideas and design them in the same moment, instead of treating them as separate phases.',
    ],
    quote: 'I want to be recognised for the quality of my work before any job title.',
    lensLabel: 'Look at my work through a lens',
    lenses: [
      {
        key: 'engineer',
        tab: 'Engineer',
        question: 'How does it work?',
        points: [
          'Software engineering fundamentals and structured problem solving',
          'Full-stack web applications with ASP.NET and Angular',
          'Clean, maintainable code and component architecture',
          'Git-based workflow and AI-assisted development',
        ],
      },
      {
        key: 'designer',
        tab: 'Designer',
        question: 'How does it feel?',
        points: [
          'User flows, wireframes and interactive prototypes in Figma',
          'Interfaces with clear hierarchy, states and feedback',
          'Design systems and visual identity',
          'Graphic design in Adobe Photoshop',
        ],
      },
      {
        key: 'product',
        tab: 'Both',
        question: 'Why does it matter?',
        points: [
          'Design decisions are made knowing how they will be built',
          'Technical constraints shape the design early — not after hand-off',
          'Functionality and user experience are delivered as one thing',
          'Clean, practical, high-quality work on both sides',
        ],
      },
    ],
  },
  stack: {
    index: '02',
    kicker: 'Stack',
    title: 'What I Use',
    intro:
      'Tools, and where I learned to use them. Each discipline shows what I work with and the courses behind it.',
    using: 'Using',
    learning: 'Learning',
    toolsLabel: 'Tools',
    learnedLabel: 'Learned through',
    reviewed: 'Reviewed by',
    inProgress: 'In progress',
    disciplines: [
      {
        key: 'design',
        name: 'Design',
        purpose: 'How it looks & feels',
        tools: [
          { t: 'Figma', note: 'Wireframing & prototyping' },
          { t: 'Adobe Photoshop' },
          { t: 'Design systems' },
          { t: 'Brand identity' },
        ],
        certs: [
          { title: 'UI/UX Design Masterclass', org: 'Udemy', by: 'Eng. Eslam Ameer', date: '2026' },
          { title: 'UI/UX Design Workshop', org: 'Zain Innovation Campus (ZINC)', by: 'Mr. Alaa Ali', date: '2026' },
          { title: 'Adobe Photoshop Course', org: 'YouTube', date: '2025' },
        ],
      },
      {
        key: 'engineering',
        name: 'Engineering',
        purpose: 'How it works',
        tools: [
          { t: 'ASP.NET', learning: true },
          { t: 'C#', learning: true },
          { t: 'Angular', learning: true },
          { t: 'TypeScript', learning: true },
          { t: 'REST APIs', learning: true },
          { t: 'React', note: 'This site' },
          { t: 'HTML5 & CSS' },
          { t: 'C++' },
        ],
        certs: [
          {
            title: 'Full Stack Developer (.NET & Angular)',
            org: 'Step by Step Company',
            by: 'Eng. Mohammad Al-Momani',
            date: 'In progress',
            live: true,
          },
        ],
      },
      {
        key: 'workflow',
        name: 'Workflow & AI',
        purpose: 'How it gets built faster',
        tools: [{ t: 'Git & GitHub' }, { t: 'Claude Code' }, { t: 'Prompt engineering' }, { t: 'Vibe coding' }],
        certs: [
          { title: 'Claude AI Mastery Course', org: 'Anthropic', date: '2026' },
          { title: 'Claude AI Prompt Engineering', org: 'YouTube', date: '2026' },
          { title: 'Vibe Coding Course', org: 'YouTube', date: '2026' },
        ],
      },
    ],
  },
  work: {
    index: '03',
    kicker: 'My Work',
    title: "What I've Built",
    intro: 'Real projects, documented honestly — the problem, what I did on each side, and how it was built.',
    labels: {
      problem: 'The problem',
      role: 'Role',
      design: 'Design',
      dev: 'Development',
      features: 'Key features',
      stack: 'Built with',
      outcome: 'Outcome',
      open: 'Read the case study',
      close: 'Close the case study',
      live: 'Visit live site',
    },
    projects: [
      {
        id: 'portfolio',
        kind: 'Design + Engineering',
        year: '2026',
        title: 'Personal portfolio',
        summary:
          'This site — designed from my own brand guide and engineered as a fast, bilingual, accessible single-page app.',
        problem:
          'A portfolio for someone who both designs and develops has to prove both at once. A template would show neither — the site itself had to be the evidence.',
        role: 'Designer & developer — end to end',
        design: [
          'Design system derived from the brand guide: palette, type scale, spacing, radius and motion tokens',
          'The brand mark turned into an interactive diagram of my process',
          'Two navigation layers: an identity header and a section dock',
          'Layouts designed per breakpoint, from 320px phones to wide screens',
        ],
        dev: [
          'React 19 + Vite with a component architecture and a single content source',
          'Full English / Arabic support with genuine right-to-left layout and brand Arabic typefaces',
          'Light & dark themes that follow the system preference and persist',
          'Keyboard navigation, focus states, reduced-motion support and semantic structure',
        ],
        features: ['Interactive brand mark', 'EN / AR with RTL', 'Light & dark themes', 'Scroll-aware dock'],
        stack: ['React 19', 'Vite', 'Framer Motion', 'CSS custom properties', 'Web3Forms'],
        outcome: 'One consistent product that presents my work — and is part of it. Deployed on Vercel.',
        link: { href: 'https://anas-portfolio-rose-nine.vercel.app/' },
      },
      {
        id: 'brand',
        kind: 'Brand & Visual identity',
        year: '2026',
        title: 'Personal brand identity',
        summary:
          'A complete visual identity — logo, palette, bilingual typography and usage rules — documented in an 11-page guide.',
        problem:
          'I needed one identity that works across my portfolio, CV and LinkedIn — in Arabic and English, on screen and in print.',
        role: 'Brand designer',
        design: [
          'Logo concept: an “A” of two lines meeting at a point, three connection nodes, and a diamond where design meets technical execution',
          'Palette extracted from the logo, with a 60 / 30 / 10 usage rule',
          'Three-typeface system: Space Grotesk, Lalezar and Changa',
          'Clear-space, minimum-size and do / don’t rules; LinkedIn cover and post templates',
        ],
        dev: [
          'Wrote the guide itself in HTML & CSS with embedded brand fonts',
          'Automated PDF and asset export with Node.js and Puppeteer scripts',
        ],
        features: ['4 official logo versions', '6-colour palette', '3 typefaces', 'Quick-spec reference sheet'],
        stack: ['Visual identity', 'Typography', 'HTML & CSS', 'Node.js', 'Puppeteer'],
        outcome: 'One consistent identity, now used across this site, my CV and my LinkedIn presence.',
        link: null,
      },
    ],
    empty: {
      title: 'Next up: full-stack projects',
      text: 'Work from my current .NET & Angular program will be documented here as it is completed.',
      cta: 'Follow on GitHub',
    },
  },
  journey: {
    index: '04',
    kicker: 'Journey',
    title: 'How I Got Here',
    intro: 'Not a list of dates — the steps where design and engineering started to become one practice.',
    here: 'You are here',
    chapters: [
      {
        key: 'foundation',
        mark: 'Start',
        tag: 'Foundation',
        title: 'Software Engineering at university',
        text: 'B.Sc. Software Engineering at Al-Zaytoonah University of Jordan — the engineering foundation everything else stands on. Now in my third year.',
      },
      {
        key: '2025',
        mark: '2025',
        tag: 'Design eye & leadership',
        title: 'Learning to see, learning to lead',
        text: 'Picked up Adobe Photoshop and graphic design, and became Academic & Technical Leader of a student team at my university.',
      },
      {
        key: '2026',
        mark: '2026',
        tag: 'Design meets code',
        title: 'The two sides connect',
        text: 'Studied UI/UX through a Udemy masterclass and a workshop at Zain Innovation Campus, brought AI into my workflow with Claude, and designed my brand identity and this portfolio end to end.',
      },
      {
        key: 'now',
        mark: 'Now',
        tag: 'Going full stack',
        title: 'Building the whole product',
        text: 'Deepening full-stack development with .NET and Angular in the Step by Step program — so I can build every layer of what I design.',
        current: true,
      },
      {
        key: '2028',
        mark: '2028',
        tag: 'Next',
        title: 'Graduation',
        text: 'Expected graduation — with a portfolio of products that are both designed and built.',
        future: true,
      },
    ],
  },
  contact: {
    index: '05',
    kicker: 'Contact',
    title: "Let's Build Something",
    intro: 'Have an idea, an internship, or a product to design and build? Tell me about it.',
    emailLabel: 'Write to me',
    copy: 'Copy email address',
    copied: 'Copied',
    elsewhere: 'Elsewhere',
    location: 'Amman, Jordan · UTC+3',
    cvWeb: 'CV — web version',
    form: {
      title: 'Or send a message here',
      name: 'Name',
      namePh: 'Your name',
      email: 'Email',
      emailPh: 'you@example.com',
      message: 'Message',
      messagePh: 'What are you working on?',
      send: 'Send message',
      sending: 'Sending…',
      errors: {
        name: 'Please enter your name.',
        email: 'Please enter a valid email address.',
        message: 'Please write a message of at least 10 characters.',
      },
      success: 'Thank you — your message was sent. I’ll get back to you soon.',
      mailtoOpened: 'Your email app should open with the message ready. If it didn’t, email me directly at',
      failure: 'The message couldn’t be sent. Please try again, or email me directly at',
      another: 'Send another message',
    },
  },
  footer: {
    signoff: 'Designed & developed by Anas Tarayra in Amman.',
    built: 'React · Vite · Space Grotesk',
    rights: 'All rights reserved.',
  },
};

const ar = {
  meta: {
    title: 'أنس الطرايرة — مطوّر Full-Stack ومصمّم UI/UX',
    description:
      'طالب هندسة برمجيات ومطوّر Full-Stack ومصمّم UI/UX في عمّان، الأردن — أحوّل الأفكار إلى تصاميم، والتصاميم إلى منتجات رقمية.',
  },
  a11y: {
    skip: 'تخطَّ إلى المحتوى',
    themeToLight: 'التبديل إلى المظهر الفاتح',
    themeToDark: 'التبديل إلى المظهر الداكن',
    language: 'اللغة',
    darkMode: 'الوضع الداكن',
    sections: 'الأقسام',
    backToTop: 'العودة للأعلى',
    newTab: '(يفتح في نافذة جديدة)',
    home: 'أنس الطرايرة — العودة للأعلى',
  },
  header: {
    name: 'أنس الطرايرة',
    role: 'مطوّر Full Stack ومصمّم UI/UX',
    cv: 'السيرة',
    cvLong: 'تحميل السيرة الذاتية',
    talk: 'لنتحدّث',
  },
  dock: {
    about: 'عنّي',
    stack: 'الأدوات',
    work: 'أعمالي',
    journey: 'المسيرة',
    contact: 'تواصل',
  },
  hero: {
    status: 'متاح للعمل والتعاون',
    name: 'أنس الطرايرة',
    roles: ['طالب هندسة برمجيات', 'مطوّر Full Stack', 'مصمّم UI/UX'],
    statement: [
      { t: 'أحوّل ' },
      { t: 'الأفكار', node: 'idea' },
      { t: ' إلى ' },
      { t: 'تصاميم', node: 'design' },
      { t: '، والتصاميم إلى ' },
      { t: 'منتجات رقمية', node: 'product' },
      { t: '.' },
    ],
    primary: 'استعرض أعمالي',
    secondary: 'تحميل السيرة الذاتية',
    info: {
      location: 'الأردن، عمّان',
      phoneLabel: 'اتصال أو واتساب',
      languagesLabel: 'اللغات',
      languages: [
        { name: 'العربية', level: 'اللغة الأم' },
        { name: 'الإنجليزية', level: 'كفاءة مهنية في العمل' },
      ],
    },
    system: {
      label: 'شعار تفاعلي: كيف تتحوّل الفكرة إلى منتج',
      hint: 'استكشف طريقة العمل',
      steps: {
        idea: {
          n: '01',
          t: 'الفكرة',
          short: 'الشرارة',
          d: 'كل منتج يبدأ بفكرة. أحوّلها إلى اتجاه واضح — المشكلة، والهيكل، ومسار الاستخدام.',
        },
        design: {
          n: '02',
          t: 'التصميم',
          short: 'التجربة',
          d: 'هنا تصبح الفكرة تجربة. أشكّل شكلها وإحساسها وطريقة عملها — في Figma، قبل أي سطر كود.',
        },
        build: {
          n: '03',
          t: 'البناء',
          short: 'النظام',
          d: 'هنا تصبح التجربة حقيقة. أبنيها بـ ‎.NET وAngular — مع الحفاظ على التصميم كما هو.',
        },
        product: {
          n: '◆',
          t: 'المنتج',
          short: 'نقطة الالتقاء',
          d: 'التصميم والبناء خطّان من حرف «A» نفسه، يلتقيان عند المعيّن — المنتج الرقمي.',
        },
      },
    },
  },
  about: {
    index: '01',
    kicker: 'عنّي',
    title: 'طريقة التفكير',
    lead: 'أفكّر بالمنتج من اتجاهين في الوقت نفسه — كيف يعمل، وكيف يُشعِر.',
    body: [
      'أنا أنس، طالب هندسة برمجيات في السنة الثالثة في جامعة الزيتونة الأردنية، ومطوّر Full-Stack أعمل بـ ‎.NET وAngular — مع شغف كبير بتصميم الواجهات وتجربة المستخدم والتصميم الجرافيكي.',
      'أؤمن أن أفضل المنتجات الرقمية تولد عندما يعمل التصميم والتطوير معًا من البداية. لذلك أبني الفكرة وأصمّمها في اللحظة نفسها، بدل التعامل معهما كمرحلتين منفصلتين.',
    ],
    quote: 'أريد أن أُعرف بجودة عملي قبل أي مسمّى وظيفي.',
    lensLabel: 'انظر إلى عملي من زاوية',
    lenses: [
      {
        key: 'engineer',
        tab: 'المهندس',
        question: 'كيف يعمل المنتج؟',
        points: [
          'أساسيات هندسة البرمجيات وحلّ المشكلات بشكل منظّم',
          'تطبيقات ويب متكاملة باستخدام ASP.NET وAngular',
          'كود نظيف وقابل للصيانة وبنية مكوّنات واضحة',
          'سير عمل مبني على Git وتطوير بمساعدة الذكاء الاصطناعي',
        ],
      },
      {
        key: 'designer',
        tab: 'المصمّم',
        question: 'كيف يُشعِر؟',
        points: [
          'مسارات الاستخدام والـ Wireframes والنماذج التفاعلية في Figma',
          'واجهات بتسلسل بصري واضح وحالات وتفاعل مدروس',
          'أنظمة التصميم والهوية البصرية',
          'التصميم الجرافيكي باستخدام Adobe Photoshop',
        ],
      },
      {
        key: 'product',
        tab: 'كلاهما',
        question: 'لماذا يهمّ ذلك؟',
        points: [
          'قرارات التصميم تُتّخذ مع معرفة كيف ستُبنى',
          'القيود التقنية تشكّل التصميم مبكرًا — لا بعد التسليم',
          'الوظيفة وتجربة المستخدم تُقدَّمان كشيء واحد',
          'عمل نظيف وعملي وعالي الجودة في الجانبين',
        ],
      },
    ],
  },
  stack: {
    index: '02',
    kicker: 'الأدوات',
    title: 'ما أستخدمه',
    intro: 'الأدوات، وأين تعلّمت استخدامها. كل تخصّص يعرض ما أعمل به والدورات التي تقف خلفه.',
    using: 'أستخدمها',
    learning: 'قيد التعلّم',
    toolsLabel: 'الأدوات',
    learnedLabel: 'تعلّمتها عبر',
    reviewed: 'بمراجعة',
    inProgress: 'قيد الإنجاز',
    disciplines: [
      {
        key: 'design',
        name: 'التصميم',
        purpose: 'كيف يبدو ويُشعِر',
        tools: [
          { t: 'Figma', note: 'Wireframes ونماذج تفاعلية' },
          { t: 'Adobe Photoshop' },
          { t: 'أنظمة التصميم' },
          { t: 'الهوية البصرية' },
        ],
        certs: [
          { title: 'UI/UX Design Masterclass', org: 'Udemy', by: 'م. إسلام أمير', date: '2026' },
          { title: 'ورشة تصميم الواجهات وتجربة المستخدم', org: 'منصة زين للإبداع (ZINC)', by: 'أ. علاء علي', date: '2026' },
          { title: 'دورة Adobe Photoshop', org: 'YouTube', date: '2025' },
        ],
      },
      {
        key: 'engineering',
        name: 'الهندسة',
        purpose: 'كيف يعمل',
        tools: [
          { t: 'ASP.NET', learning: true },
          { t: 'C#', learning: true },
          { t: 'Angular', learning: true },
          { t: 'TypeScript', learning: true },
          { t: 'REST APIs', learning: true },
          { t: 'React', note: 'هذا الموقع' },
          { t: 'HTML5 & CSS' },
          { t: 'C++' },
        ],
        certs: [
          {
            title: 'مطوّر Full Stack ‏(.NET & Angular)',
            org: 'شركة Step by Step',
            by: 'م. محمد المومني',
            date: 'قيد الإنجاز',
            live: true,
          },
        ],
      },
      {
        key: 'workflow',
        name: 'سير العمل والذكاء الاصطناعي',
        purpose: 'كيف يُبنى أسرع',
        tools: [{ t: 'Git & GitHub' }, { t: 'Claude Code' }, { t: 'هندسة الأوامر' }, { t: 'Vibe Coding' }],
        certs: [
          { title: 'Claude AI Mastery Course', org: 'Anthropic', date: '2026' },
          { title: 'هندسة الأوامر لـ Claude', org: 'YouTube', date: '2026' },
          { title: 'دورة Vibe Coding', org: 'YouTube', date: '2026' },
        ],
      },
    ],
  },
  work: {
    index: '03',
    kicker: 'أعمالي',
    title: 'ما بنيته',
    intro: 'مشاريع حقيقية موثّقة بصدق — المشكلة، وما قدّمته في كل جانب، وكيف بُنيت.',
    labels: {
      problem: 'المشكلة',
      role: 'الدور',
      design: 'التصميم',
      dev: 'التطوير',
      features: 'أبرز الميزات',
      stack: 'التقنيات',
      outcome: 'النتيجة',
      open: 'اقرأ دراسة الحالة',
      close: 'إغلاق دراسة الحالة',
      live: 'زيارة الموقع',
    },
    projects: [
      {
        id: 'portfolio',
        kind: 'تصميم + هندسة',
        year: '2026',
        title: 'الموقع الشخصي',
        summary:
          'هذا الموقع — مصمّم انطلاقًا من دليل هويتي البصرية، ومبني كتطبيق صفحة واحدة سريع وثنائي اللغة وسهل الوصول.',
        problem:
          'موقع لشخص يصمّم ويطوّر يجب أن يثبت الأمرين معًا. القالب الجاهز لا يثبت أيًّا منهما — كان على الموقع نفسه أن يكون الدليل.',
        role: 'مصمّم ومطوّر — من البداية للنهاية',
        design: [
          'نظام تصميم مشتق من دليل الهوية: الألوان، مقاييس الخطوط، المسافات، الزوايا والحركة',
          'تحويل الشعار إلى مخطّط تفاعلي يشرح طريقة عملي',
          'طبقتا تنقّل: ترويسة للهوية وشريط عائم للأقسام',
          'تخطيطات مصمّمة لكل مقاس، من هواتف 320px إلى الشاشات العريضة',
        ],
        dev: [
          'React 19 وVite ببنية مكوّنات ومصدر محتوى واحد',
          'دعم كامل للعربية والإنجليزية مع اتجاه حقيقي من اليمين لليسار وخطوط الهوية العربية',
          'مظهر فاتح وداكن يتبع إعدادات النظام ويُحفظ',
          'تنقّل بلوحة المفاتيح، حالات تركيز واضحة، دعم تقليل الحركة وبنية دلالية',
        ],
        features: ['شعار تفاعلي', 'عربي / إنجليزي', 'مظهر فاتح وداكن', 'شريط تنقّل يتبع التمرير'],
        stack: ['React 19', 'Vite', 'Framer Motion', 'CSS custom properties', 'Web3Forms'],
        outcome: 'منتج واحد متّسق يعرض أعمالي — وهو جزء منها. منشور على Vercel.',
        link: { href: 'https://anas-portfolio-rose-nine.vercel.app/' },
      },
      {
        id: 'brand',
        kind: 'هوية بصرية',
        year: '2026',
        title: 'الهوية البصرية الشخصية',
        summary: 'هوية بصرية كاملة — شعار، ألوان، نظام خطوط ثنائي اللغة وقواعد استخدام — موثّقة في دليل من 11 صفحة.',
        problem:
          'احتجت هوية واحدة تعمل عبر موقعي وسيرتي الذاتية وLinkedIn — بالعربية والإنجليزية، على الشاشة وفي الطباعة.',
        role: 'مصمّم الهوية',
        design: [
          'فكرة الشعار: حرف A من خطين يلتقيان بنقطة، وثلاث نقاط اتصال، ومعيّن يرمز لالتقاء التصميم بالتنفيذ التقني',
          'لوحة ألوان مستخرجة من الشعار مع قاعدة استخدام 60 / 30 / 10',
          'نظام من ثلاثة خطوط: Space Grotesk وLalezar وChanga',
          'قواعد مساحة الأمان والحد الأدنى للحجم والاستخدام الصحيح والخاطئ، وقوالب LinkedIn',
        ],
        dev: ['كتبت الدليل نفسه بـ HTML وCSS مع تضمين خطوط الهوية', 'أتمتة تصدير ملف PDF والأصول باستخدام Node.js وPuppeteer'],
        features: ['4 نسخ رسمية للشعار', '6 ألوان', '3 خطوط', 'جدول مواصفات سريع'],
        stack: ['هوية بصرية', 'الطباعة والخطوط', 'HTML & CSS', 'Node.js', 'Puppeteer'],
        outcome: 'هوية واحدة متّسقة، أستخدمها الآن في هذا الموقع وسيرتي الذاتية وحضوري على LinkedIn.',
        link: null,
      },
    ],
    empty: {
      title: 'التالي: مشاريع Full-Stack',
      text: 'سأوثّق هنا أعمال برنامج ‎.NET وAngular الحالي عند اكتمالها.',
      cta: 'تابعني على GitHub',
    },
  },
  journey: {
    index: '04',
    kicker: 'المسيرة',
    title: 'كيف وصلت إلى هنا',
    intro: 'ليست قائمة تواريخ — بل الخطوات التي بدأ فيها التصميم والهندسة يصبحان ممارسة واحدة.',
    here: 'أنت هنا',
    chapters: [
      {
        key: 'foundation',
        mark: 'البداية',
        tag: 'الأساس',
        title: 'هندسة البرمجيات في الجامعة',
        text: 'بكالوريوس هندسة البرمجيات في جامعة الزيتونة الأردنية — الأساس الهندسي الذي يقوم عليه كل شيء. أدرس حاليًا في السنة الثالثة.',
      },
      {
        key: '2025',
        mark: '2025',
        tag: 'عين المصمّم والقيادة',
        title: 'أتعلّم أن أرى، وأن أقود',
        text: 'تعلّمت Adobe Photoshop والتصميم الجرافيكي، وأصبحت قائدًا أكاديميًا وتقنيًا لفريق طلابي في جامعتي.',
      },
      {
        key: '2026',
        mark: '2026',
        tag: 'التصميم يلتقي بالكود',
        title: 'الجانبان يتّصلان',
        text: 'درست تصميم الواجهات وتجربة المستخدم عبر دورة على Udemy وورشة في منصة زين للإبداع، وأدخلت الذكاء الاصطناعي إلى سير عملي مع Claude، وصمّمت هويتي البصرية وهذا الموقع من البداية للنهاية.',
      },
      {
        key: 'now',
        mark: 'الآن',
        tag: 'نحو Full Stack',
        title: 'بناء المنتج كاملًا',
        text: 'أعمّق تطوير Full-Stack بـ ‎.NET وAngular في برنامج Step by Step — لأبني كل طبقة مما أصمّمه.',
        current: true,
      },
      {
        key: '2028',
        mark: '2028',
        tag: 'التالي',
        title: 'التخرّج',
        text: 'التخرّج المتوقّع — مع مجموعة من المنتجات المصمّمة والمبنيّة معًا.',
        future: true,
      },
    ],
  },
  contact: {
    index: '05',
    kicker: 'تواصل',
    title: 'لنبنِ شيئًا معًا',
    intro: 'لديك فكرة، أو فرصة تدريب، أو منتج تريد تصميمه وبناءه؟ حدّثني عنه.',
    emailLabel: 'راسلني',
    copy: 'نسخ البريد الإلكتروني',
    copied: 'تم النسخ',
    elsewhere: 'في أماكن أخرى',
    location: 'عمّان، الأردن · UTC+3',
    cvWeb: 'السيرة الذاتية — نسخة الويب',
    form: {
      title: 'أو أرسل رسالة من هنا',
      name: 'الاسم',
      namePh: 'اسمك',
      email: 'البريد الإلكتروني',
      emailPh: 'you@example.com',
      message: 'الرسالة',
      messagePh: 'على ماذا تعمل؟',
      send: 'إرسال الرسالة',
      sending: 'جارٍ الإرسال…',
      errors: {
        name: 'يرجى إدخال اسمك.',
        email: 'يرجى إدخال بريد إلكتروني صحيح.',
        message: 'يرجى كتابة رسالة من 10 أحرف على الأقل.',
      },
      success: 'شكرًا لك — وصلت رسالتك، وسأردّ عليك قريبًا.',
      mailtoOpened: 'يُفترض أن يفتح تطبيق البريد والرسالة جاهزة. إن لم يحدث، راسلني مباشرة على',
      failure: 'تعذّر إرسال الرسالة. حاول مجددًا، أو راسلني مباشرة على',
      another: 'إرسال رسالة أخرى',
    },
  },
  footer: {
    signoff: 'صمّمه وطوّره أنس الطرايرة في عمّان.',
    built: 'React · Vite · Changa',
    rights: 'جميع الحقوق محفوظة.',
  },
};

export const content = { en, ar };
